services:
  agendar:
    build: .
    container_name: agendar_bayron
    restart: always
    ports:
      - "4321:4321"
    env_file: .env
    volumes:
      - bayron_data:/data

volumes:
  bayron_data:
